# Generated by Django 5.2.7 on 2025-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveylink_remove_question_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveylink',
            name='survey_id',
            field=models.CharField(max_length=255),
        ),
    ]
