# Generated by Django 5.2.7 on 2025-11-07 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveylink_survey_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveylink',
            name='id',
        ),
        migrations.AddField(
            model_name='surveylink',
            name='link',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='surveylink',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
